/* ================= SHANGHAI (transit, outbound) ================= */
var CITYINTRO = {
 sh:["Không phải điểm đến, mà là <strong>15 tiếng quá cảnh giữa hai chuyến bay China Eastern</strong> - và đủ dài để thành một ngày Thượng Hải thật sự. Cả bốn người hạ cánh Phố Đông 06:35, về khách sạn cạnh sân bay gửi đồ, rồi Tuấn Anh ở lại ngủ bù còn ba người kia đi một vòng thành phố và quay về đón trước chuyến bay tối. Nhiệt độ cuối tháng 10 khoảng 15–23°C.",
     "Not a destination but a <strong>15-hour connection between two China Eastern flights</strong> - and long enough to become a real day in Shanghai. All four land at Pudong at 06:35, drop their bags at a hotel by the airport, then Tuan Anh stays to catch up on sleep while the other three do a loop of the city and come back for him before the evening flight. Late October is 15–23°C.",
     "这不是目的地，而是<strong>两班东航航班之间15小时的中转</strong>——却长得足以变成真正的上海一日。四人06:35降落浦东，在机场旁的酒店寄存行李，俊英留下补觉，另外三人进城绕一圈，晚班机前回来接他。10月下旬约15–23°C。"],
 bj:["Cuối tháng 10 Bắc Kinh khoảng 5–17°C, khô và trong - mùa đẹp nhất trong năm, nhưng sáng sớm lạnh và có gió. Campus Xương Bình của BNU nằm ở ga Sa Hà <span class=\"han\">沙河</span> trên tuyến Xương Bình, cách trung tâm khoảng một tiếng, nhưng lại rất gần Trường Thành và khu đại học Hải Điến ở phía bắc. <strong>BNU đã xác nhận sẽ đón cả bốn người ngay tại sân bay Thủ Đô và đưa thẳng về campus nhận phòng</strong>, nên đêm hạ cánh không phải lo gì.",
     "Late October in Beijing is 5–17°C, dry and clear - the best season of the year, though early mornings are cold and windy. BNU's Changping campus sits at Shahe <span class=\"han\">沙河</span> on the Changping Line, about an hour from the centre, but very close to the Great Wall and the Haidian university district in the north. <strong>BNU has confirmed it will collect all four at Capital Airport and drive them straight to campus to check in</strong>, so the arrival night needs no planning.",
     "10月下旬北京5–17°C，干燥晴朗——一年中最好的季节，但清晨寒冷有风。北师大昌平校区位于昌平线沙河站，距市中心约一小时，却离长城和北部海淀高校区很近。<strong>北师大已确认将在首都机场接四人并直接送回校区办理入住</strong>，所以落地当晚无需另作安排。"],
 tj:["Ba ngày cuối chỉ còn một mình Mỹ Duyên. Vé về của em ấy <strong>cất cánh từ Thiên Tân chứ không phải Bắc Kinh</strong>, quá cảnh qua đêm ở Thâm Quyến rồi mới về Hà Nội sáng 1/11. Phần Thâm Quyến em ấy tự sắp xếp; phần dưới đây chỉ lo đúng hai việc mà lịch bay bắt buộc: sang Thiên Tân đúng lúc, và không lỡ chuyến 07:55.",
     "The last three days are My Duyen alone. Her return <strong>departs from Tianjin, not Beijing</strong>, with an overnight connection in Shenzhen before landing in Hanoi on the morning of 1 Nov. She is arranging the Shenzhen part herself; what follows covers only the two things the flights force: getting to Tianjin in time, and not missing the 07:55 departure.",
     "最后三天只剩美缘一人。她的回程<strong>从天津起飞，而不是北京</strong>，在深圳过夜中转后于11月1日上午抵达河内。深圳部分由她自行安排；下面只处理航班决定的两件事：按时到达天津，以及不要误了07:55的航班。"]
};

var DAYS = [
{ city:"sh", n:"21", dow:"T4", icon:"g-pearl",
  head:["Bay đêm, rồi trọn một ngày ở Thượng Hải","A night flight, then a whole day in Shanghai","红眼航班，然后是完整的上海一日"],
  intro:["Chuyến bay rời Nội Bài lúc 02:20, nên thực tế phải có mặt ở sân bay từ khoảng 23:30 tối 20/10. Cả bốn người đi cùng nhau suốt chặng này. Lịch trong ngày lấy đúng theo bản đồ hành trình nhóm đã dựng: đi xa trước, vòng dần về phía đông, tránh đi lại lắt léo.",
   "The flight leaves Noi Bai at 02:20, so in practice you are at the airport from about 23:30 on the evening of 20 Oct. All four travel together on this leg. The day follows the route map the group drew up: farthest first, then looping back east, avoiding backtracking.",
   "航班02:20离开内排，所以实际上10月20日晚约23:30就要到机场。这一段四人同行。当天行程完全按团队自己绘制的路线图：先远后近，逐步向东折返，避免绕路。"],
  slots:[
   {t:["23:30","23:30","23:30"], b:["Có mặt ở Nội Bài T2, tối 20/10","At Noi Bai T2, evening of 20 Oct","10月20日晚抵达内排T2"],
    d:["Đặt trước xe ra sân bay từ chiều 20/10. Đây là chuyến bay đêm nên hôm đó nên ngủ sớm hoặc chấp nhận thức trắng.",
       "Book the ride to the airport during the afternoon of 20 Oct. This is a red-eye, so either sleep early that day or accept a night without it.",
       "10月20日下午就订好去机场的车。这是红眼航班，当天要么早睡，要么接受熬夜。"]},
   {t:["02:20 → 06:35","02:20 → 06:35","02:20 → 06:35"], b:["Nội Bài T2 → Phố Đông T1 · MU5076","Noi Bai T2 → Pudong T1 · MU5076","内排T2 → 浦东T1 · MU5076"], dur:["3 giờ 15","3h15","3小时15分"],
    d:["China Eastern, Boeing 738, có suất ăn. Bay 2 giờ 15 phút cộng chênh lệch múi giờ 1 tiếng. Giờ Trung Quốc nhanh hơn Việt Nam 1 tiếng - mọi mốc giờ trong trang này đều là giờ Trung Quốc.",
       "China Eastern, Boeing 738, meal served. 2h15 in the air plus the 1-hour time difference. China is 1 hour ahead of Vietnam - every time on this page is China time.",
       "中国东方航空，波音738，含餐。飞行2小时15分，加1小时时差。中国比越南快1小时——本页所有时间均为中国时间。"]},
   {t:["06:35–07:50","06:35–07:50","06:35–07:50"], b:["Nhập cảnh Trung Quốc, lấy hành lý","Chinese immigration and baggage","入境中国、取行李"], dur:["75 phút","75 min","75分钟"],
    d:["Đây là điểm nhập cảnh Trung Quốc duy nhất của cả chuyến và cũng là nơi lấy vân tay. Giữ kỹ tờ khai và dấu nhập cảnh. Sân bay ghi hành lý ký gửi đi thẳng tới Bắc Kinh, nhưng lịch của nhóm lại tính cả thời gian lấy hành lý - cứ để nguyên 75 phút này, thừa thì tốt.",
       "This is the trip's only entry into China and where fingerprints are taken. Keep the arrival card and entry stamp safe. The airline lists the checked bag as running straight through to Beijing, yet the group's own plan allows time to collect it - keep the 75 minutes either way; spare time here is a gift.",
       "这是全程唯一一次入境中国，也是采集指纹的地方。妥善保管入境卡和入境章。航司标注托运行李直挂北京，但团队自己的计划留了取行李的时间——无论如何保留这75分钟，多出来是好事。"]},
   {m:1, t:["20 phút","20 min","20分钟"], a:["Xe đưa đón miễn phí của khách sạn từ Phố Đông về Dihang Boutique Hotel · 9,2 km · liên hệ khách sạn ngay khi hạ cánh, hoặc đặt trước từ Việt Nam",
    "The hotel's free shuttle from Pudong to the Dihang Boutique Hotel · 9.2 km · call the hotel on landing, or arrange it before leaving Vietnam",
    "酒店免费接驳车从浦东到迪航酒店 · 9.2公里 · 落地后立即联系酒店，或从越南出发前先约好"]},
   {t:["08:20–08:40","08:20–08:40","08:20–08:40"], b:["Dihang Boutique Hotel: gửi đồ, Tuấn Anh nhận phòng","Dihang Boutique Hotel: drop bags, Tuan Anh checks in","迪航酒店：寄存行李，俊英入住"], tag:"pay", tagx:["487.164 ₫ / phòng","VND 487,164 / room","487,164越南盾/间"], dur:["20 phút","20 min","20分钟"],
    d:["<span class=\"han\">上海浦东国际机场迪航酒店</span>. Một phòng hai giường đơn, đặt đứng tên Trần Tuấn Anh, huỷ miễn phí trước 23:00 ngày 21/10. Ba người kia gửi đồ ở đây rồi đi tiếp, chiều quay lại đón. Chia đều bốn người là khoảng 122 nghìn mỗi người.",
       "<span class=\"han\">上海浦东国际机场迪航酒店</span>. One twin room, booked in Tran Tuan Anh's name, free cancellation until 23:00 on 21 Oct. The other three leave their bags here and collect both bags and Tuan Anh in the afternoon. Split four ways it is about 122,000 VND each.",
       "<span class=\"han\">上海浦东国际机场迪航酒店</span>。一间双床房，以陈俊英名义预订，10月21日23:00前免费取消。另外三人把行李存在这里，下午回来取行李并接人。四人均摊每人约12.2万越南盾。"]}
  ],
  legs:[
   { cls:"uni", p:["gb","md"], h:["Một vòng Thượng Hải, ba người","A loop of Shanghai, three people","上海一圈，三人同行"], who:["Gia Bảo + Quỳnh Mai + Mỹ Duyên","Gia Bao + Quynh Mai + My Duyen","嘉宝 + 琼梅 + 美缘"],
     intro:["Tuyến đường đi xa nhất trước rồi quay dần về phía đông, không đi ngược lại lần nào: thư viện và khu tô giới Pháp buổi sáng, Rockbund và Nam Kinh Đông Lộ buổi trưa, Lục Gia Chủy đúng lúc hoàng hôn. Chỉ có một cuốc Didi dài lúc đầu ngày; phần còn lại là đi bộ, ba cuốc ngắn và một ga tàu.",
      "The route runs farthest-first and loops back east with nothing retraced: the library and the French Concession in the morning, the Rockbund and East Nanjing Road at midday, Lujiazui exactly at sunset. Only the first ride is a long Didi; the rest is walking, three short hops and one metro stop.",
      "路线先远后近、逐步东折，全程不走回头路：上午图书馆和法租界，中午外滩源和南京东路，傍晚正好到陆家嘴。只有一天之初那段滴滴较长，其余是步行、三段短途和一站地铁。"],
     slots:[
      {t:["08:40","08:40","08:40"], b:["Rời khách sạn Dihang, tay không","Leave the Dihang with empty hands","轻装离开迪航酒店"],
       d:["Vali kéo gửi lại khách sạn, chỉ mang túi nhỏ và sạc dự phòng. Trời Thượng Hải cuối tháng 10 khoảng 15–23°C, sáng sớm hơi lạnh nên mang theo một lớp áo mỏng.",
          "The wheeled cases stay at the hotel; take a small bag and a power bank only. Shanghai in late October is 15–23°C and cool first thing, so carry one light layer.",
          "拉杆箱留在酒店，只带小包和充电宝。10月下旬上海约15–23°C，清早偏凉，带一件薄外套。"]},
      {m:1, t:["50–60 phút","50–60 min","50–60分钟"], a:['Didi thẳng từ khách sạn tới <span class="han">上海图书馆</span> Thư viện Thượng Hải · 42 km · 190–240 CNY cả xe, chia ba còn 65–80 CNY mỗi người · đặt xe từ trong sảnh khách sạn',
        'A single Didi from the hotel to <span class="han">上海图书馆</span> Shanghai Library · 42 km · CNY 190–240 for the car, CNY 65–80 each split three ways · book it from the hotel lobby',
        '从酒店打一辆滴滴直达<span class="han">上海图书馆</span> · 42公里 · 整车190–240元，三人分摊每人65–80元 · 在酒店大堂就叫车']},
      {t:["Rẻ hơn","Cheaper","更省"], b:["Hoặc đi tàu đệm và metro","Or the maglev and metro","或坐磁浮加地铁"],
       d:['Xe đưa đón ra Phố Đông → tàu đệm tới <span class="han">龙阳路</span> → tuyến 2 → đổi tuyến 10 tại <span class="han">南京东路</span> → ga <span class="han">上海图书馆</span>. Khoảng 85 phút và 50 CNY một người, tức <strong>rẻ hơn khoảng 25 CNY nhưng tới nơi lúc 10:10</strong>, muộn gần một tiếng và mất luôn phần thư viện. Với quỹ thời gian một ngày duy nhất ở Thượng Hải thì nên đi Didi.',
          'Hotel shuttle to Pudong → maglev to <span class="han">龙阳路</span> Longyang Road → Line 2 → change to Line 10 at <span class="han">南京东路</span> → <span class="han">上海图书馆</span>. About 85 minutes and CNY 50 a head, so <strong>about CNY 25 cheaper but arriving at 10:10</strong>, nearly an hour later and without the library. With one single day in Shanghai, take the Didi.',
          '酒店接驳车到浦东 → 磁浮到<span class="han">龙阳路</span> → 2号线 → <span class="han">南京东路</span>换10号线 → <span class="han">上海图书馆</span>站。约85分钟、每人50元，也就是<strong>省约25元但10:10才到</strong>，晚了近一小时，图书馆也去不成。只有一天的上海，还是打车。']},
      {t:["09:15–10:00","09:15–10:00","09:15–10:00"], b:["Thư viện Thượng Hải","Shanghai Library","上海图书馆"], tag:"free", dur:["45 phút","45 min","45分钟"],
       d:['<span class="han">上海图书馆</span> ở số 1555 đường Hoài Hải Trung, mở cửa từ 8:30, vào tự do, chỉ cần gửi túi ở tủ. Toà nhà 1996 có tháp đôi và sảnh lớn; phần đáng xem là khu đọc mở và không khí một thư viện đang được dùng thật vào sáng thứ tư. Ngay trên ga tuyến 10 cùng tên, và cách Vũ Khang Đại Lâu đúng 800m đi bộ - đó là lý do nó mở đầu ngày hôm nay.',
          '<span class="han">上海图书馆</span> at 1555 Middle Huaihai Road opens at 08:30, free to enter, bags into a locker. The 1996 building has its twin towers and a big hall; what is worth seeing is the open reading floor and the feel of a library actually in use on a Wednesday morning. It sits directly on the Line 10 station of the same name, exactly 800m walk from Wukang Mansion - which is why it opens the day.',
          '<span class="han">上海图书馆</span>位于淮海中路1555号，8:30开馆，免费入内，包存柜子即可。1996年的建筑有双塔和大厅；值得看的是开架阅览区，以及周三上午一座真正在被使用的图书馆的氛围。它就在同名的10号线车站上方，步行到武康大楼正好800米——这就是它排在今天开头的原因。']},
      {m:1, t:["10 phút","10 min","10分钟"], a:["Đi bộ 800m theo đường Hoài Hải Trung về phía tây tới ngã năm Vũ Khang","An 800m walk west along Middle Huaihai Road to the Wukang junction","沿淮海中路向西步行800米到武康路口"]},
      {t:["10:10–10:50","10:10–10:50","10:10–10:50"], b:["Toà nhà Vũ Khang","Wukang Mansion","武康大楼"], tag:"free", dur:["40 phút","40 min","40分钟"],
       d:['<span class="han">武康大楼</span>——toà nhà hình mũi tàu xây năm 1924 ở góc đường Vũ Khang, kiến trúc sư Ladislav Hudec. Đây là công trình được chụp ảnh nhiều nhất khu tô giới Pháp cũ; góc kinh điển là từ bên kia ngã năm nhìn chéo lên. Quanh đó là những con đường rợp bóng cây ngô đồng, đi bộ rất dễ chịu.',
          '<span class="han">武康大楼</span> - the ship-prow building of 1924 on Wukang Road by the architect Ladislav Hudec. It is the most photographed building in the old French Concession; the classic angle is diagonally across the five-way junction. The plane-tree streets around it are pleasant to walk.',
          '<span class="han">武康大楼</span>——1924年由建筑师邬达克设计的船头形建筑，位于武康路口。这是原法租界最上镜的建筑；经典机位是在五岔路口斜对面。周边梧桐成荫的马路很适合散步。']},
      {m:1, t:["12 phút","12 min","12分钟"], a:["Didi tới HAUS NOWHERE · 2,8 km · 20–30 CNY cả xe","Didi to HAUS NOWHERE · 2.8 km · CNY 20–30 for the car","打滴滴到 HAUS NOWHERE · 2.8公里 · 整车20–30元"]},
      {t:["11:00–11:45","11:00–11:45","11:00–11:45"], b:["HAUS NOWHERE","HAUS NOWHERE","HAUS NOWHERE"], tag:"free", dur:["45 phút","45 min","45分钟"],
       d:["Không gian bán lẻ theo kiểu concept store, kiến trúc và trưng bày là phần đáng xem chứ không phải hàng hoá. Vào cửa tự do, chủ yếu để chụp ảnh và xem cách người ta làm không gian.",
          "A concept-store retail space where the architecture and the display are the point rather than the merchandise. Free to enter; mostly for photographs and for seeing how the space is put together.",
          "概念店式的零售空间，看点在建筑和陈列而不是商品。免费入内，主要是拍照和看空间的做法。"]},
      {m:1, t:["25 phút","25 min","25分钟"], a:["Didi tới khu Sa Mỹ · 5,5 km · 30–40 CNY cả xe · đây là chặng nối duy nhất mà metro đi vòng hẳn một vòng lớn",
        "Didi to the Shama area · 5.5 km · CNY 30–40 for the car · the one link where the metro takes a long detour",
        "打滴滴到沙美一带 · 5.5公里 · 整车30–40元 · 这一段地铁要绕一大圈"]},
      {t:["12:15–13:45","12:15–13:45","12:15–13:45"], b:["Sa Mỹ, đường Viên Minh Viên và Nhà thờ Hiệp Tiến","Shama, Yuanmingyuan Road and Union Church","沙美、圆明园路与协进堂"], tag:"free", dur:["90 phút","90 min","90分钟"],
       d:['<span class="han">圆明园路</span>——dãy phố Rockbund ngay sau lưng Bến Thượng Hải, gồm khoảng mười toà nhà thương mại đầu thế kỷ 20 đã được trùng tu, cùng <span class="han">协进堂</span> Nhà thờ Hiệp Tiến xây năm 1886. Phố đi bộ, ít xe, kiến trúc dày đặc - đây là đoạn cho ảnh đẹp nhất trong ngày mà lại vắng hơn Bến Thượng Hải.',
          '<span class="han">圆明园路</span> - the Rockbund strip directly behind the Bund: about ten restored early-twentieth-century commercial buildings plus <span class="han">协进堂</span> Union Church of 1886. Pedestrianised, little traffic, dense architecture - the best stretch of the day for photographs and quieter than the Bund itself.',
          '<span class="han">圆明园路</span>——外滩正后方的外滩源街区，约十栋修缮过的20世纪初商业建筑，以及1886年的<span class="han">协进堂</span>。步行街、车少、建筑密集——是当天最出片的一段，也比外滩本身安静。']},
      {m:1, t:["15 phút","15 min","15分钟"], a:["Đi bộ ra bờ kè Bến Thượng Hải, chụp vài kiểu, rồi rẽ vào đầu phố Nam Kinh Đông Lộ",
        "Walk out to the Bund promenade, take a few frames, then turn into the head of East Nanjing Road",
        "步行到外滩堤岸拍几张，再拐进南京东路街口"]},
      {t:["14:00–15:30","14:00–15:30","14:00–15:30"], b:["Đường Nam Kinh Đông và ăn trưa","East Nanjing Road and lunch","南京东路与午餐"], tag:"free", dur:["90 phút","90 min","90分钟"],
       d:['<span class="han">南京东路</span>——phố đi bộ nối thẳng từ Bến Thượng Hải vào trung tâm, 1,2 km, có tàu điện nhỏ chạy dọc phố. Ăn trưa ở đây là hợp lý vì cả buổi sáng chưa dừng ăn: tiểu long bao và sinh tiễn bao là đặc sản riêng của Thượng Hải, tìm quán trong các ngõ cắt ngang thay vì mặt phố lớn thì rẻ hơn nhiều. Ăn xong còn khoảng 40 phút đi bộ và chụp ảnh.',
          '<span class="han">南京东路</span> - the pedestrian street running from the Bund into the centre, 1.2 km, with a small tram along it. Lunch belongs here because the morning had no stop for it: xiaolongbao and shengjianbao are Shanghai specialities, and the side lanes are much cheaper than the main frontage. That leaves about 40 minutes to walk and photograph.',
          '<span class="han">南京东路</span>——从外滩通向市中心的步行街，1.2公里，街上有观光小火车。午饭安排在这里，因为整个上午都没停下来吃：小笼包和生煎包是上海特色，横向的小巷比大马路便宜得多。吃完还有约40分钟散步拍照。']},
      {m:1, t:["10 phút","10 min","10分钟"], a:['Tuyến 2 từ <span class="han">南京东路</span> đi một ga sang <span class="han">陆家嘴</span> Lục Gia Chủy · 3 CNY',
        'Line 2 one stop from <span class="han">南京东路</span> to <span class="han">陆家嘴</span> Lujiazui · CNY 3',
        '2号线从<span class="han">南京东路</span>坐一站到<span class="han">陆家嘴</span> · 3元']},
      {t:["16:00–17:30","16:00–17:30","16:00–17:30"], b:["Lục Gia Chủy, dưới chân tháp Đông Phương Minh Châu","Lujiazui, under the Oriental Pearl Tower","陆家嘴，东方明珠脚下"], tag:"free", dur:["90 phút","90 min","90分钟"],
       d:["Điểm cuối và cũng là điểm đáng dừng lâu nhất: 35 phút ở chân tháp, 35 phút trên cầu đi bộ vòng tròn Lục Gia Chủy - đây là góc ngước lên tháp mà ai cũng nhận ra - phần còn lại nghỉ chân. Mặt trời lặn khoảng 17:05 nên đúng khung này ánh nắng xiên vàng lên mặt kính các toà tháp, và tới 17:30 thì đèn bắt đầu bật. Không cần mua vé lên tháp, góc đẹp nhất là từ dưới đất và từ cầu vòng.",
          "The last stop and the one worth lingering on: 35 minutes at the foot of the tower, 35 on the circular Lujiazui skywalk, which is the looking-up shot everyone knows, the rest sitting down. Sunset is around 17:05, so this window catches the low sun turning the glass gold, and by 17:30 the lights start coming on. No need to buy a ticket up the tower; the best angles are from the ground and the skywalk.",
          "最后一站，也最值得多待：塔下35分钟，陆家嘴环形天桥35分钟（那是人人都认得的仰拍机位），其余时间坐下休息。约17:05日落，这个时段正好斜阳把玻璃幕墙映成金色，到17:30灯就陆续亮起。不必买登塔票，最好的角度就在地面和天桥上。"]},
      {m:1, t:["45 phút","45 min","45分钟"], a:['Tuyến 2 từ Lục Gia Chủy quay về phía đông tới ga <span class="han">凌空路</span> · 5 CNY · rời Lục Gia Chủy muộn nhất 17:35',
        'Line 2 east from Lujiazui back to <span class="han">凌空路</span> Lingkong Road · CNY 5 · leave Lujiazui by 17:35 at the latest',
        '2号线从陆家嘴向东回<span class="han">凌空路</span>站 · 5元 · 最晚17:35离开陆家嘴']},
      {m:1, t:["15 phút","15 min","15分钟"], a:["Didi từ Lăng Không Lộ về khách sạn Dihang · 4,2 km · 20–30 CNY cả xe","Didi from Lingkong Road back to the Dihang · 4.2 km · CNY 20–30 for the car","从凌空路打滴滴回迪航酒店 · 4.2公里 · 整车20–30元"]}
     ]},
   { cls:"home", p:["ta"], h:["Ngủ bù ở khách sạn","Catching up on sleep at the hotel","在酒店补觉"], who:["Tuấn Anh","Tuan Anh","俊英"],
     slots:[
      {t:["08:40–18:00","08:40–18:00","08:40–18:00"], b:["Nghỉ tại phòng ở Dihang Boutique Hotel","Resting in the room at the Dihang Boutique Hotel","在迪航酒店房间休息"], dur:["hơn 9 tiếng","over 9 hours","9小时以上"],
       d:["Sau chuyến bay đêm cất cánh 02:20 thì đây là quyết định đúng: ngủ một giấc tử tế trước khi bay tiếp lúc 21:35 và về tới campus BNU lúc gần 01:00 sáng. Phòng đặt đứng tên Tuấn Anh nên nhận phòng không vướng gì.",
          "After a red-eye that left at 02:20 this is the right call: a proper sleep before the 21:35 onward flight and a campus arrival near 01:00. The room is in Tuan Anh's name, so checking in is straightforward.",
          "在02:20起飞的红眼航班之后，这是正确的选择：在21:35的后续航班和将近凌晨1点抵达校区之前好好睡一觉。房间以俊英名义预订，入住没有障碍。"]},
      {t:["Gợi ý","Suggestion","建议"], b:["Đặt chuông trước 17:30","Set an alarm for before 17:30","把闹钟定在17:30前"],
       d:["Ba bạn kia về tới khách sạn khoảng 18:35 và cả nhóm lên xe ra sân bay lúc 19:00. Dậy sớm hơn một tiếng để kịp thu dọn và ăn nhẹ.",
          "The other three are back around 18:35 and the whole group leaves for the airport at 19:00. Wake an hour earlier to pack up and eat something.",
          "另外三人约18:35回来，全队19:00出发去机场。提前一小时起床收拾并吃点东西。"]}
     ]}
  ],
  tail:[
   {t:["18:35–19:00","18:35–19:00","18:35–19:00"], b:["Cả bốn người gặp lại, lấy hành lý ở khách sạn","All four meet up and collect the bags","四人会合，在酒店取行李"], dur:["25 phút","25 min","25分钟"]},
   {m:1, t:["25 phút","25 min","25分钟"], a:["Xe đưa đón miễn phí của khách sạn ra Phố Đông · 9,2 km · xác nhận giờ chạy từ sáng","The hotel's free shuttle to Pudong · 9.2 km · confirm the departure time in the morning","酒店免费接驳车到浦东 · 9.2公里 · 早上就确认发车时间"]},
   {t:["19:30","19:30","19:30"], b:["Có mặt ở Phố Đông T1","At Pudong T1","抵达浦东T1"], dur:["sớm 2 giờ","2h05 early","提前2小时5分"],
    d:["Chặng Thượng Hải đi Bắc Kinh là bay nội địa nên hai tiếng là đủ, miễn là hành lý đã đi thẳng từ Hà Nội và chỉ cần qua an ninh. <strong>Nếu phải ký gửi lại thì phải có mặt sớm hơn</strong>: rời Lục Gia Chủy lúc 17:00 thay vì 17:35, tới sân bay khoảng 19:00. Xác nhận việc này ngay lúc làm thủ tục ở Nội Bài, đừng để tới Thượng Hải mới biết.",
       "Shanghai to Beijing is a domestic leg, so two hours is enough provided the bags ran straight through from Hanoi and it is only security. <strong>If they have to be rechecked, come earlier</strong>: leave Lujiazui at 17:00 rather than 17:35, reaching the airport around 19:00. Settle this at check-in in Hanoi rather than finding out in Shanghai.",
       "上海飞北京是国内航段，两小时足够，前提是行李从河内直挂、只需过安检。<strong>若需重新托运就要更早到</strong>：17:00而不是17:35离开陆家嘴，约19:00到机场。这件事在内排值机时就问清楚，别到上海才发现。"]},
   {t:["21:35 → 23:50","21:35 → 23:50","21:35 → 23:50"], b:["Phố Đông T1 → Thủ Đô T2 · MU5165","Pudong T1 → Capital T2 · MU5165","浦东T1 → 首都T2 · MU5165"], dur:["2 giờ 15","2h15","2小时15分"],
    d:["China Eastern, Airbus A320-212. Hạ cánh Bắc Kinh 23:50, BNU đón ngay tại sân bay.",
       "China Eastern, Airbus A320-212. Landing in Beijing at 23:50, where BNU meets the group at the airport.",
       "中国东方航空，空客A320-212。23:50抵达北京，北师大在机场接机。"]}
  ],
  callouts:[
   { p:["gb","md","ta"],
     h:["Giờ nhận phòng ghi sau 13:00, nhưng kế hoạch cần từ 08:30","Check-in is listed as after 13:00, but the plan needs 08:30","登记入住写的是13:00后，但计划需要8:30"],
     b:[["Phiếu đặt phòng ghi <strong>nhận phòng sau 13:00 ngày 21/10, trả phòng trước 14:00 ngày 22/10</strong>. Nhưng cả kế hoạch xoay quanh việc gửi đồ và cho Tuấn Anh vào phòng ngủ từ khoảng 08:30 sáng - tức là <strong>sớm hơn bốn tiếng rưỡi so với giờ chuẩn</strong>.",
       "The booking states <strong>check-in after 13:00 on 21 Oct, check-out before 14:00 on 22 Oct</strong>. But the whole plan turns on dropping the bags and getting Tuan Anh into the room from about 08:30 - <strong>four and a half hours before the standard time</strong>.",
       "订单写明<strong>10月21日13:00后入住，22日14:00前退房</strong>。但整个计划的前提是约8:30就寄存行李并让俊英进房休息——<strong>比标准时间早四个半小时</strong>。"],
      ["Khách sạn cạnh sân bay thường quen với khách quá cảnh và hay linh động, nhưng đây không phải điều mặc nhiên có. Nếu không được nhận phòng sớm thì phương án dự phòng là gửi hành lý ở lễ tân (hầu hết khách sạn nhận) và Tuấn Anh ngồi chờ ở sảnh tới 13:00 - vẫn dùng được, chỉ là mất bốn tiếng nghỉ.",
       "Airport hotels are used to transit guests and often flexible, but this is not automatic. If early check-in is refused, the fallback is leaving the bags at reception, which most hotels accept, and Tuan Anh waiting in the lobby until 13:00 - workable, but four hours of rest lost.",
       "机场旁的酒店习惯接待中转客人，通常比较灵活，但这并非理所当然。若不能提前入住，退而求其次是把行李存在前台（大多数酒店都收），俊英在大堂等到13:00——仍可行，只是少了四小时休息。"]],
     fix:["<strong>Nhắn cho khách sạn ngay tuần này</strong>, nói rõ hai việc: xin nhận phòng khoảng 08:30 ngày 21/10, và xác nhận xe đưa đón sân bay có chạy vào khung 07:50 sáng lẫn 17:50 chiều hay không. Nhân tiện hỏi luôn: phòng đặt cho 2 người lớn nhưng sẽ có 4 người vào gửi đồ, khách sạn có yêu cầu gì thêm không.",
      "<strong>Message the hotel this week</strong> and settle two things: ask for check-in around 08:30 on 21 Oct, and confirm the airport shuttle runs both at about 07:50 in the morning and 17:50 in the afternoon. While you are at it: the room is booked for 2 adults but 4 people will come in to leave bags - ask whether they need anything for that.",
      "<strong>本周就联系酒店</strong>，落实两件事：申请10月21日8:30左右入住，并确认机场接驳车在早上约7:50和下午17:50两个时段都有车。顺便问清：房间订的是2位成人，但会有4人进来寄存行李，酒店是否另有要求。"]
   }
  ]
}
];
