DAYS.push(
{ city:"bj", n:"26", dow:"T2", icon:"g-wall",
  head:["Ngày cả đội tách làm ba hướng","The day the team splits three ways","全队分三路的一天"],
  intro:["Hôm nay là <strong>thứ hai - Cố Cung đóng cửa</strong>, nên đây đúng là ngày để đi Trường Thành và Universal. Cả ba rời BNU cùng lúc 7:30 rồi đi ba hướng khác nhau, và tối gặp lại nhau ở khách sạn Thông Châu.",
   "Today is <strong>Monday - the Forbidden City is closed</strong>, which makes it exactly the right day for the Great Wall and Universal. All three leave BNU together at 07:30, go three separate ways, and meet again in the evening at the hotel in Tongzhou.",
   "今天是<strong>周一——故宫闭馆</strong>，正好适合去长城和环球影城。三人7:30一同离开北师大，分三路行动，晚上在通州的酒店会合。"],
  legs:[
   { cls:"wall", p:["gb"], h:["Trường Thành, rồi khu đại học Hải Điến","The Great Wall, then the Haidian university district","长城，然后海淀高校区"], who:["Gia Bảo + Quỳnh Mai","Gia Bao + Quynh Mai","嘉宝 + 琼梅"],
     intro:["Chọn Bát Đạt Lĩnh vì từ Xương Bình có tàu cao tốc lên thẳng. Và vì tàu về dừng ở ga Thanh Hà - cách khu đại học Hải Điến đúng hai ga tàu - nên buổi chiều ghép được cả hai cổng trường lẫn Viên Minh Viên mà gần như không tốn thêm đường đi. Kế hoạch dưới đây <strong>không phụ thuộc vào việc xin được suất vào trong trường</strong>: chỉ chụp ảnh ở cổng ngoài, rồi dành phần lớn thời gian cho Viên Minh Viên, nơi ai cũng mua vé vào được.",
      "Badaling because there is a direct high-speed train from Changping. And because the train back stops at Qinghe - two stops from the Haidian university district - the afternoon can take in both university gates and the Old Summer Palace at almost no extra travel. The plan below <strong>does not depend on securing a campus visit slot</strong>: photographs at the outer gates, then most of the time at the Old Summer Palace, which anyone can buy a ticket for.",
      "选八达岭是因为从昌平有高铁直达。而回程列车停靠清河站——距海淀高校区仅两站——所以下午可以顺路看两所大学的校门并逛圆明园，几乎不用多走路。下面的安排<strong>不依赖能否约到入校名额</strong>：只在校门外拍照，其余时间放在人人都能买票进入的圆明园。"],
     slots:[
      {t:["07:30–08:00","07:30–08:00","07:30–08:00"], b:["Trả phòng BNU, mang hành lý theo","Check out of BNU with luggage","退宿舍，带上行李"], dur:["30 phút","30 min","30分钟"]},
      {m:1, t:["40 phút","40 min","40分钟"], a:['Sa Hà → tuyến Xương Bình → đổi tuyến 13 → ga <span class="han">清河</span> Thanh Hà · 5 CNY',
        'Shahe → Changping Line → change to Line 13 → <span class="han">清河</span> Qinghe · CNY 5',
        '沙河 → 昌平线 → 换13号线 → <span class="han">清河</span>站 · 5元']},
      {t:["08:45–09:10","08:45–09:10","08:45–09:10"], b:["Gửi hành lý ở tủ tại ga Thanh Hà","Lockers at Qinghe station","清河站行李寄存"], dur:["25 phút","25 min","25分钟"],
       d:["Khoảng 20–30 CNY một tủ. Đừng vác vali lên Trường Thành - và chiều đi thăm trường đại học cũng cần tay không.",
          "About CNY 20–30 a locker. Do not carry suitcases up the Wall - and the campus visits in the afternoon need free hands too.",
          "每个柜约20–30元。别把行李箱背上长城——下午逛校园也需要空手。"]},
      {m:1, t:["30 phút","30 min","30分钟"], a:["Tàu cao tốc Thanh Hà → ga Bát Đạt Lĩnh Trường Thành · 16–25 CNY · đặt qua app 12306 bằng hộ chiếu, mở bán trước 15 ngày",
        "High-speed train Qinghe → Badaling Great Wall · CNY 16–25 · book on the 12306 app with your passport, released 15 days ahead",
        "高铁清河→八达岭长城站 · 16–25元 · 用12306App凭护照购买，提前15天放票"]},
      {m:1, t:["20 phút","20 min","20分钟"], a:["Từ sân ga lên mặt đất rồi tới cổng soát vé - ga nằm sâu 100m dưới lòng núi, riêng thang cuốn đã mất 8 phút",
        "From platform to surface and on to the gate - the station is 100m inside the mountain and the escalators alone take 8 minutes",
        "从站台上到地面再到检票口——车站在山体内100米深，仅扶梯就要8分钟"]},
      {t:["10:10–13:10","10:10–13:10","10:10–13:10"], b:["Trường Thành Bát Đạt Lĩnh","Badaling Great Wall","八达岭长城"], tag:"pay", tagx:["40 CNY","CNY 40","40元"], dur:["180 phút","180 min","180分钟"],
       d:["Mở cửa 6:30–16:30. Chia thời gian: 100 phút đi hướng <em>bắc</em> lên tháp canh số 8 Hảo Hán Pha - đoạn kinh điển và cao nhất; 50 phút hướng nam, vắng hơn, dốc hơn, ảnh đẹp hơn vì ít người; 30 phút nghỉ và ăn nhẹ. Cáp treo khoảng 100 CNY khứ hồi - đi bộ được thì tiết kiệm khoản này.",
          "Open 6:30–16:30. Split it: 100 minutes <em>north</em> to watchtower 8, Haohanpo, the classic and highest stretch; 50 minutes south, emptier, steeper, better photographs because of the space; 30 minutes to rest and snack. The cable car is about CNY 100 return - walk it and save that.",
          "开放6:30–16:30。时间分配：向<em>北</em>100分钟至八楼好汉坡，最经典也最高的一段；向南50分钟，人少、更陡、因为空旷更好拍；30分钟休息吃点东西。缆车往返约100元——能走就省下这笔。"]},
      {m:1, t:["50 phút","50 min","50分钟"], a:["Ra ga, xuống sân ga, tàu về Thanh Hà","Back to the station, down to the platform, train to Qinghe","返回车站下到站台，乘车回清河"]},
      {m:1, t:["10 phút","10 min","10分钟"], a:['Tuyến 13 từ Thanh Hà, hai ga, tới <span class="han">五道口</span> Wudaokou · 3 CNY',
        'Line 13 from Qinghe, two stops, to <span class="han">五道口</span> Wudaokou · CNY 3',
        '13号线从清河两站至<span class="han">五道口</span> · 3元']},
      {m:1, t:["15 phút","15 min","15分钟"], a:["Đi bộ hoặc thuê xe đạp chung từ Wudaokou về phía tây theo đường Thanh Hoa Tây · 1,5 km",
        "Walk or grab a shared bike west from Wudaokou along Qinghua West Road · 1.5 km",
        "从五道口步行或扫共享单车沿清华西路向西 · 1.5公里"]},
      {t:["14:30–15:00","14:30–15:00","14:30–15:00"], b:["Cổng Tây Đại học Thanh Hoa","Tsinghua University West Gate","清华大学西门"], tag:"free", dur:["30 phút","30 min","30分钟"],
       d:['<span class="han">清华大学西门</span> - cổng đá trắng có biển <span class="han">清华大学</span>, nằm ngay mặt đường nên <strong>chụp ảnh từ bên ngoài không cần vé hay đặt chỗ</strong>. Đây cũng chính là chỗ người ta xếp hàng chụp ảnh hằng ngày. Lưu ý thành thật: <span class="han">二校门</span> Nhị Hiệu Môn - cổng đá trắng nổi tiếng hơn - nằm sâu khoảng 500m bên trong khuôn viên, không vào thì không thấy được.',
          '<span class="han">清华大学西门</span> - the white stone gate with the <span class="han">清华大学</span> plaque, right on the street, so <strong>photographing it from outside needs no ticket and no reservation</strong>. This is where people queue for the shot every day. One honest caveat: <span class="han">二校门</span>, the more famous white gate, stands about 500m inside the campus and cannot be seen without entering.',
          '<span class="han">清华大学西门</span> - 带<span class="han">清华大学</span>校名牌匾的白色石门，就在马路边，<strong>从校外拍照无需门票或预约</strong>。每天都有人在此排队拍照。需如实说明：更有名的<span class="han">二校门</span>在校园内约500米处，不入校看不到。']},
      {m:1, t:["10 phút","10 min","10分钟"], a:["Đi bộ xuống phía nam sang đường Di Hoà Viên, tới cổng Tây Bắc Đại",
        "Walk south onto Yiheyuan Road to Peking University's West Gate",
        "向南步行至颐和园路，到北京大学西门"]},
      {t:["15:10–15:40","15:10–15:40","15:10–15:40"], b:["Cổng Tây Đại học Bắc Kinh","Peking University West Gate","北京大学西门"], tag:"free", dur:["30 phút","30 min","30分钟"],
       d:['<span class="han">北京大学西门</span> - may hơn Thanh Hoa: cổng nổi tiếng nhất của Bắc Đại lại chính là cổng ngoài, kiểu cung đình mái ngói đỏ có đôi sư tử đá, biển chữ <span class="han">北京大学</span> do Mao Trạch Đông viết. Đứng ngoài chụp thoải mái. Hồ Vị Danh và tháp Bác Nhã thì ở bên trong, chỉ xem được nếu vào.',
          '<span class="han">北京大学西门</span> - luckier than Tsinghua: PKU\'s most famous gate is the outer one, a palace-style gate with red tiles and a pair of stone lions, the <span class="han">北京大学</span> plaque in Mao Zedong\'s hand. Photograph it freely from the street. Weiming Lake and Boya Pagoda are inside and need entry.',
          '<span class="han">北京大学西门</span> - 比清华幸运：北大最有名的校门正是外面这座，宫殿式红瓦、一对石狮，<span class="han">北京大学</span>匾额为毛泽东题写。在街边随意拍照。未名湖和博雅塔在校内，须入校才能看。']},
      {m:1, t:["6 phút","6 min","6分钟"], a:['Đi bộ ngược lên phía bắc qua đường, tới cổng nam Viên Minh Viên <span class="han">绮春园宫门</span>',
        'Walk back north across the road to the Old Summer Palace south gate <span class="han">绮春园宫门</span>',
        '向北过马路到圆明园南门<span class="han">绮春园宫门</span>']},
      {t:["15:45–17:10","15:45–17:10","15:45–17:10"], b:["Viên Minh Viên","The Old Summer Palace","圆明园"], tag:"pay", tagx:["10 + 15 CNY","CNY 10 + 15","10 + 15元"], dur:["85 phút","85 min","85分钟"],
       d:['<span class="han">圆明园</span> - cung điện mùa hè cũ của nhà Thanh, bị liên quân Anh–Pháp đốt năm 1860 và để nguyên dạng phế tích từ đó. Đây là điểm <strong>ai cũng vào được, chỉ cần hộ chiếu và 10 CNY</strong>, không đặt chỗ, không cần quen ai - nên nó gánh phần lớn buổi chiều. Vé vào vườn 10 CNY, thêm 15 CNY cho khu <span class="han">西洋楼</span> Tây Dương Lâu, nơi có nền đá chạm trổ kiểu baroque của <span class="han">大水法</span> - bức ảnh mà ai cũng nhận ra. Cuối tháng 10 lá vàng và đỏ quanh hồ. Nên dành 55 phút cho khu phế tích, 30 phút đi bộ ven hồ về cổng.',
          '<span class="han">圆明园</span> - the Qing dynasty\'s old summer palace, burnt by Anglo-French troops in 1860 and left as ruins ever since. <strong>Anyone can enter with a passport and CNY 10</strong> - no reservation, no contacts needed - so it carries most of the afternoon. Garden entry is CNY 10, plus CNY 15 for the <span class="han">西洋楼</span> Western Mansions, where the carved baroque stonework of <span class="han">大水法</span> stands - the photograph everyone recognises. Late October brings yellow and red around the lakes. Give 55 minutes to the ruins and 30 walking back along the water.',
          '<span class="han">圆明园</span> - 清代的旧夏宫，1860年被英法联军焚毁，此后保留废墟原貌。<strong>凭护照花10元人人可进</strong>——无需预约，也不需要熟人——所以它承担了下午的大部分时间。园门票10元，<span class="han">西洋楼</span>遗址区另加15元，那里有<span class="han">大水法</span>的巴洛克式雕花石构——最有辨识度的一张照片。10月下旬湖畔黄红交映。建议遗址区55分钟，沿湖步行返回30分钟。']},
      {m:1, t:["25 phút","25 min","25分钟"], a:["Đi bộ hoặc xe đạp chung quay lại ga Wudaokou","Walk or ride a shared bike back to Wudaokou station","步行或骑共享单车返回五道口站"]},
      {m:1, t:["25 phút","25 min","25分钟"], a:["Tuyến 13 hai ga về ga Thanh Hà, lấy hành lý ở tủ · 3 CNY","Line 13 two stops back to Qinghe, collect the luggage · CNY 3","13号线两站回清河站取行李 · 3元"]},
      {m:1, t:["100 phút","100 min","100分钟"], a:['Tuyến 13 → đổi tuyến 10 tại <span class="han">知春路</span> → đổi tuyến 1 tại <span class="han">国贸</span> → ga <span class="han">梨园</span> Lê Viên · 7 CNY · đây là chặng dài nhất trong ngày, cái giá của việc ở Thông Châu',
        'Line 13 → change to Line 10 at <span class="han">知春路</span> Zhichunlu → change to Line 1 at <span class="han">国贸</span> Guomao → <span class="han">梨园</span> Liyuan · CNY 7 · the longest ride of the day, the price of staying in Tongzhou',
        '13号线 → <span class="han">知春路</span>换10号线 → <span class="han">国贸</span>换1号线 → <span class="han">梨园</span>站 · 7元 · 全天最长的一段，住通州的代价']},
      {t:["19:45–20:15","19:45–20:15","19:45–20:15"], b:["Nhận phòng khách sạn Thông Châu","Check in at the Tongzhou hotel","入住通州酒店"], dur:["30 phút","30 min","30分钟"],
       d:["Khách sạn cách ga Lê Viên khoảng 350m nên xuống tàu là tới. Nếu muốn về sớm hơn thì rút ngắn Viên Minh Viên khoảng 30 phút.",
          "The hotel is about 350m from Liyuan station, so it is a short walk from the train. To get back earlier, trim about 30 minutes off the Old Summer Palace.",
          "酒店距梨园站约350米，下车即到。想早点回来，可把圆明园的时间压缩约30分钟。"]},
      {t:["20:30–21:30","20:30–21:30","20:30–21:30"], b:["Ăn tối gần khách sạn cùng Mỹ Duyên","Dinner near the hotel with My Duyen","与美缘在酒店附近吃晚饭"], dur:["60 phút","60 min","60分钟"],
       d:["Hôm nay đi bộ nhiều và leo Trường Thành, nên ăn gần rồi về phòng sớm. Mỹ Duyên rời công viên lúc 20:00 và về tới khoảng 20:25. Muốn xem khu cổng Universal thì đổi thành ăn ở CityWalk, cách bốn ga tàu và mở tới 21:30, nhưng sẽ về muộn hơn khoảng 40 phút.",
          "A long day with the Wall in it, so eat nearby and get to bed. My Duyen leaves the park at 20:00 and is back around 20:25. To see the area by the Universal gate instead, eat at CityWalk, four stops away and open until 21:30, though that gets you back about 40 minutes later.",
          "今天走了很多路还爬了长城，就近吃完早点回房。美缘20:00出园，约20:25到。若想看看环球影城门口一带，可改在城市大道用餐，四站地铁、开到21:30，但会晚回约40分钟。"]}
     ]},
   { cls:"uni", p:["md"], h:["Universal Beijing Resort","Universal Beijing Resort","北京环球影城"], who:["Mỹ Duyên","My Duyen","美缘"],
     intro:["Cả ngày ở công viên, và cái quyết định duy nhất thật sự quan trọng là <strong>có mặt đúng giờ mở cửa</strong>. Từ campus Xương Bình ra tới cổng Universal là quãng đường dài nhất trong cả chuyến đi Bắc Kinh - gần 60 km, xuyên từ tây bắc xuống đông nam - nên giờ khởi hành phải tính ngược từ giờ mở cổng chứ không phải từ giờ ngủ dậy.",
      "A whole day in the park, and the one decision that really matters is <strong>being there when it opens</strong>. Changping campus to the Universal gate is the longest journey of the entire Beijing stay - nearly 60 km from the north-west to the south-east - so the departure time has to be worked backwards from the gate, not forwards from waking up.",
      "在园区待一整天，唯一真正重要的决定是<strong>开门就到</strong>。从昌平校区到环球影城门口是整个北京行程中最长的一段——近60公里，从西北穿到东南——所以出发时间要从开园时间倒推，而不是从起床时间往后算。"],
     slots:[
      {t:["06:20–07:00","06:20–07:00","06:20–07:00"], b:["Dậy, ăn sáng, trả phòng BNU","Up, breakfast, check out of BNU","起床、早餐、退宿舍"], dur:["40 phút","40 min","40分钟"],
       d:["Trả phòng cùng cả nhóm nhưng đi sớm hơn hai bạn kia khoảng 30 phút, vì chặng đường của bạn dài hơn hẳn.",
          "Check out with the group but leave about 30 minutes ahead of the other two, because your journey is much the longer one.",
          "和大家一起退房，但比另外两人早约30分钟出发，因为你的路程长得多。"]},
      {m:1, t:["75–85 phút","75–85 min","75–85分钟"], a:["Didi từ campus Xương Bình thẳng tới cổng Universal · 58 km · 200–250 CNY · đặt xe từ tối hôm trước cho khung 07:00",
        "A Didi from the Changping campus straight to the Universal gate · 58 km · CNY 200–250 · pre-book it the night before for 07:00",
        "从昌平校区打滴滴直达环球影城门口 · 58公里 · 200–250元 · 前一晚就预约07:00的车"]},
      {t:["Rẻ hơn","Cheaper","更省"], b:["Hoặc đi metro, nhưng phải dậy sớm hơn 45 phút","Or the metro, but 45 minutes earlier out of bed","或坐地铁，但要早起45分钟"], dur:["120 phút","120 min","120分钟"],
       d:['Sa Hà → tuyến Xương Bình → tuyến 8 tại <span class="han">朱辛庄</span> → đổi tuyến 1 tại <span class="han">王府井</span> → đi thẳng tới ga cuối <span class="han">环球度假区</span> · 8 CNY. Khoảng 2 tiếng, tức phải rời BNU lúc <strong>06:15</strong> mới có mặt lúc 08:20. Rẻ hơn khoảng 200 CNY. Ở ga cuối nên đứng toa số 15 để ra thẳng thang cuốn cửa B, sát ngay cổng an ninh.',
          'Shahe → Changping Line → Line 8 at <span class="han">朱辛庄</span> Zhuxinzhuang → change to Line 1 at <span class="han">王府井</span> Wangfujing → ride to the terminus <span class="han">环球度假区</span> · CNY 8. About two hours, so leaving BNU at <strong>06:15</strong> to be there by 08:20. Saves roughly CNY 200. At the terminus, stand in car 15 to come out at the exit B escalator, right by security.',
          '沙河 → 昌平线 → <span class="han">朱辛庄</span>换8号线 → <span class="han">王府井</span>换1号线 → 坐到终点<span class="han">环球度假区</span> · 8元。约两小时，也就是要<strong>06:15</strong>离开北师大才能08:20到。省约200元。到终点站时站第15节车厢，出站直达B口扶梯，紧邻安检。']},
      {t:["08:30","08:30","08:30"], b:["Có mặt ở cổng Universal Beijing","At the Universal Beijing gate","抵达北京环球影城门口"],
       d:["Gửi vali ngay trong công viên, 90 CNY một kiện lớn cả ngày - đừng kéo vali đi chơi. Xếp hàng an ninh trước giờ mở cổng khoảng 30 phút là vừa.",
          "Store the suitcase inside the park, CNY 90 for a large bag all day - do not drag it around. Being in the security queue about 30 minutes before opening is right.",
          "行李箱存在园内，大件全天90元——别拖着到处走。开园前约30分钟排进安检队伍正合适。"]},
      {t:["09:00–20:00","09:00–20:00","09:00–20:00"], b:["Universal Beijing Resort","Universal Beijing Resort","北京环球影城"], tag:"pay", tagx:["418–528 CNY","CNY 418–528","418–528元"], dur:["11 tiếng","11 hours","11小时"],
       d:["<strong>Kiểm tra giờ mở cửa trên app trước một tuần:</strong> công viên mở 9:00 vào ngày cao điểm nhưng 10:00 vào ngày thường mùa thấp điểm, và 26/10 là thứ hai cuối tháng 10. Nếu app ghi 10:00 thì lùi toàn bộ buổi sáng lại một tiếng, đỡ phải dậy lúc 6:20. Giờ đầu tiên trong ngày là lúc vắng nhất, đáng giá hơn bất cứ mẹo xếp hàng nào. Giá vé thay đổi theo ngày, tra lịch giá 90 ngày trên app trước khi đặt.",
          "<strong>Check the opening time in the app a week ahead:</strong> the park opens at 09:00 on peak days but 10:00 on low-season weekdays, and 26 Oct is a late-October Monday. If the app says 10:00, push the whole morning back an hour and skip the 06:20 alarm. The first hour is the emptiest and beats any queueing trick. Prices vary by date; check the 90-day price calendar in the app before booking.",
          "<strong>提前一周在App里确认开园时间：</strong>旺季9:00开园，淡季工作日10:00，而10月26日是10月下旬的周一。若App显示10:00，整个上午就往后推一小时，也不用6:20起床。第一个小时人最少，胜过任何排队技巧。票价按日浮动，订票前先看App里的90天价格日历。"]},
      {t:["Cân nhắc","Optional","可选"], b:["Express Pass","Express Pass","优速通"], tag:"pay", tagx:["từ 900 CNY","from CNY 900","900元起"],
       d:["Thứ hai cuối tháng 10 là ngày thường mùa thấp điểm nên hàng chờ vốn đã dễ thở, và hàng <em>Single Rider</em> - lợi thế thật sự khi đi một mình - đã giải quyết được phần lớn các trò lớn. Nếu vẫn muốn chắc chắn chơi hết mọi thứ trong 11 tiếng thì Express Pass là cách mua thời gian.",
          "A Monday in late October is a low-season weekday, so the queues are already manageable, and the <em>Single Rider</em> lines - the real advantage of going alone - cover most of the big rides. If you want certainty of doing everything in eleven hours, Express Pass is how you buy time.",
          "10月下旬的周一是淡季工作日，排队本就不算长，而<em>单人排队通道</em>——独自前往的真正优势——已能解决大部分大型项目。若想确保十一小时内玩遍所有项目，优速通就是花钱买时间。"]},
      {t:["20:00–20:30","20:00–20:30","20:00–20:30"], b:['CityWalk <span class="han">城市大道</span>','CityWalk <span class="han">城市大道</span>','城市大道 CityWalk'], tag:"free", dur:["30 phút","30 min","30分钟"],
       d:["Khu ăn uống ngay cổng công viên, mở tới 21:30, không cần vé. Lấy vali ở quầy gửi đồ rồi mua đồ lưu niệm trước khi về.",
          "The dining strip right at the park gate, open to 21:30, no ticket needed. Collect the suitcase from storage and grab souvenirs before heading in.",
          "园区门口的餐饮街，开到21:30，无需门票。取回行李箱，买点纪念品再走。"]},
      {m:1, t:["25 phút","25 min","25分钟"], a:['Tuyến 1 đi bốn ga về ga <span class="han">梨园</span> Lê Viên, đi bộ 350m về khách sạn · 3 CNY · đây chính là lý do chọn khách sạn ở Thông Châu',
        'Line 1 four stops back to <span class="han">梨园</span> Liyuan, then a 350m walk to the hotel · CNY 3 · this is the whole reason for a Tongzhou hotel',
        '1号线坐四站回<span class="han">梨园</span>站，步行350米到酒店 · 3元 · 这正是选择通州酒店的理由']},
      {t:["≈ 21:00","≈ 21:00","约21:00"], b:["Về tới khách sạn Thông Châu, gặp lại hai bạn kia","At the Tongzhou hotel with the others","抵达通州酒店，与另两人会合"],
       d:["Gia Bảo và Quỳnh Mai về trước khoảng một tiếng. Hôm nay là ngày dài nhất của bạn trong cả chuyến - ngủ sớm, mai 6:15 đã phải rời khách sạn.",
          "Gia Bao and Quynh Mai got back about an hour earlier. Today is your longest day of the whole trip - sleep early, tomorrow starts at 06:15.",
          "嘉宝和琼梅早约一小时回来。今天是全程最长的一天——早点睡，明天6:15就要出门。"]}
     ]},
   { cls:"home", p:["ta"], h:["Bay về Hà Nội","Fly home to Hanoi","飞回河内"], who:["Tuấn Anh","Tuan Anh","俊英"],
     slots:[
      {t:["07:30","07:30","07:30"], b:["Trả phòng BNU cùng cả nhóm","Check out of BNU with the others","与大家一同退宿舍"],
       d:["Ba người kia đi ga Sa Hà, Tuấn Anh tách ra ở đây. Chào tạm biệt xong là ai đi đường nấy.",
          "The other three head for Shahe station; Tuan Anh splits off here. Say goodbye and go your separate ways.",
          "另外三人去沙河站，俊英在这里分开。道别之后各走各的路。"]},
      {m:1, t:["45–120 phút","45–120 min","45–120分钟"], a:["Xương Bình → sân bay Thủ Đô · taxi khoảng 45 phút, 150 CNY · hoặc tuyến Xương Bình → tuyến 13 → tàu nhanh sân bay, khoảng 2 tiếng, 32 CNY",
        "Changping → Capital Airport · taxi about 45 min, CNY 150 · or Changping Line → Line 13 → Airport Express, about 2h, CNY 32",
        "昌平 → 首都机场 · 打车约45分钟150元 · 或昌平线→13号线→机场快轨，约2小时32元"]},
      {t:["Trước 3 tiếng","3 hours ahead","提前3小时"], b:["Có mặt ở sân bay Thủ Đô","At Capital Airport","抵达首都机场"],
       d:["Chuyến quốc tế nên tính sớm 3 tiếng. Vé về của Tuấn Anh chưa đặt: Vietnam Airlines VN513 và Air China CA741 đều bay thẳng về Nội Bài, cất cánh khoảng giữa trưa tới đầu giờ chiều. Chốt vé rồi thì trừ ngược lại giờ rời campus.",
          "An international departure, so allow 3 hours. His ticket is not booked yet: Vietnam Airlines VN513 and Air China CA741 both fly direct to Noi Bai, leaving around midday to early afternoon. Once the ticket is fixed, work the campus departure time backwards from it.",
          "国际航班，提前3小时。他的机票尚未预订：越南航空VN513和国航CA741都直飞内排，起飞时间约在中午至下午早些时候。订好票后再倒推离开校区的时间。"]}
     ]}
  ],
  callouts:[
   { p:["gb","md"],
     h:["Khách sạn 26–27/10: Thông Châu, cạnh Universal","Hotels 26–27 Oct: Tongzhou, next to Universal","10月26–27日住宿：通州，紧邻环球影城"],
     b:[["Đặt <strong>một phòng gia đình ở khu Lê Viên, quận Thông Châu, cho cả hai đêm 26 và 27/10</strong>. Khách sạn cách ga Lê Viên khoảng 350m và cách cổng Universal đúng bốn ga tàu, nên Mỹ Duyên ra khỏi công viên lúc 20:00 là về tới phòng sau 25 phút, không cần bắt xe. Phòng gia đình 1 giường đôi và 1 giường đơn ở khu này khoảng 300–440 CNY một đêm, rẻ hơn khu Tiền Môn chừng 60–100 CNY mỗi đêm.",
       "Book <strong>one family room around Liyuan in Tongzhou district for both nights, 26 and 27 October</strong>. The hotel is about 350m from Liyuan station and exactly four stops from the Universal gate, so My Duyen is in her room 25 minutes after leaving the park at 20:00, with no car needed. A family room with one double and one single runs about CNY 300–440 a night here, roughly CNY 60–100 cheaper per night than around Qianmen.",
       "在<strong>通州区梨园一带订一间家庭房，26日和27日两晚都住</strong>。酒店距梨园站约350米，离环球影城正好四站，美缘20:00出园后25分钟即可回房，不必打车。此处一大床加一单床的家庭房约300–440元一晚，比前门一带每晚便宜约60–100元。"],
      ["Cái giá nằm ở ngày 27/10: cả ngày diễn ra ở trung tâm, mà Lê Viên cách đó khoảng 20 ga tàu, nên riêng hôm đó mất thêm khoảng <strong>hai tiếng ngồi tàu</strong> so với ở Tiền Môn, và phải rời khách sạn lúc 6:15. Ngày 28/10 thì không ảnh hưởng nhiều vì dù ở đâu cũng phải ra sân bay Thủ Đô. Lịch hai ngày đó bên dưới đã tính đúng theo phương án metro.",
       "The cost lands on 27 October: the whole day is downtown and Liyuan is about 20 stops away, so that day alone adds roughly <strong>two hours of train time</strong> compared with Qianmen, and means leaving the hotel at 06:15. 28 October is barely affected, since the run to Capital Airport is long from anywhere. The schedules for both days below are written for the metro version.",
       "代价集中在10月27日：整天都在市中心，而梨园离那里约20站，光那一天就比住前门多约<strong>两小时车程</strong>，而且要6:15出门。10月28日影响不大，因为无论住哪里都要去首都机场。下面这两天的安排都是按地铁方案写的。"],
      ["Phòng này hết vào sáng 28/10. Nhưng vé CA883 cất cánh 00:10 ngày 28/10, nên <strong>Gia Bảo và Quỳnh Mai chỉ dùng phòng tới 20:00 ngày 27/10 rồi đi luôn</strong> - đêm 27/10 hai bạn ở trên máy bay, còn Mỹ Duyên ngủ lại một mình. Từ đêm 28/10 Mỹ Duyên <strong>cần đặt phòng riêng</strong>, và lúc đó không còn lý do gì phải ở Thông Châu nữa.",
       "The room ends on the morning of 28 October. But CA883 leaves at 00:10 on 28 Oct, so <strong>Gia Bao and Quynh Mai only use the room until 20:00 on 27 October and then go</strong> - they spend that night in the air while My Duyen has the room to herself. From the night of 28 October she <strong>needs her own booking</strong>, and by then there is no reason to stay in Tongzhou.",
       "这间房到10月28日上午结束。但CA883在10月28日00:10起飞，所以<strong>嘉宝和琼梅只用到10月27日20:00就走了</strong>——那一晚他们在飞机上，美缘独自住这间房。从10月28日晚起美缘<strong>需要单独订房</strong>，到那时也没有理由再住通州。"]],
     fix:["<strong>Nếu bạn người Bắc Kinh lái xe đưa đi ngày 27/10 thì phần thiệt này biến mất gần hết</strong>, và Thông Châu trở thành lựa chọn đúng cả về tiền lẫn thời gian. Xem ghi chú về xe ở ngày 27 bên dưới. Khi đặt phòng, lọc khách sạn ghi rõ <em>“guests from all countries/regions are welcome”</em> và khai đủ 3 khách.",
      "<strong>If your Beijing friend drives on 27 October, most of that penalty disappears</strong>, and Tongzhou becomes the right call on both money and time. See the notes on the car under day 27 below. When booking, filter for hotels stating <em>“guests from all countries/regions are welcome”</em> and declare all 3 guests.",
      "<strong>如果北京的朋友在10月27日开车接送，这个代价基本消失</strong>，通州在钱和时间上都成为正确选择。见下面27日关于用车的说明。订房时请筛选注明<em>“接待所有国家/地区客人”</em>的酒店，并如实申报3人入住。"]
   },
   { p:["gb"],
     h:["Nếu ở cuộc thi gặp được sinh viên Thanh Hoa hay Bắc Đại","If you meet a Tsinghua or PKU student at the competition","若在比赛中认识清华或北大的同学"],
     b:[["Kế hoạch chiều 26/10 ở trên cố tình không cần vào trong trường. Nhưng nếu trong bốn ngày ở BNU mà quen được ai đang học Thanh Hoa hoặc Bắc Đại thì mọi thứ mở ra: sinh viên và giảng viên hai trường đều được mời khách qua hệ thống nội bộ, và đây là con đường mà người nước ngoài vẫn dùng để vào - nhanh hơn và chắc hơn hẳn so với tự đăng ký.",
       "The afternoon plan above deliberately needs no campus entry. But if over the four days at BNU you get to know anyone studying at Tsinghua or PKU, it opens up: students and staff at both universities can invite guests through an internal system, and that is how foreign visitors normally get in - faster and far more reliable than registering yourself.",
       "上面的下午安排刻意不需要入校。但如果在北师大的四天里认识了清华或北大的在读同学，情况就不同了：两校师生都可通过内部系统邀请访客，外籍访客通常正是走这条路进去的——比自己预约快得多也可靠得多。"],
      ["Tự đăng ký thì vướng thật: cả hai trường bắt đặt chỗ trước qua mini-program trên WeChat - <span class=\"han\">参观清华</span> và <span class=\"han\">参观北大</span> - nhưng hệ thống của Thanh Hoa hiện chỉ nhận chứng minh thư đại lục, không nhận hộ chiếu nước ngoài (khách Hồng Kông, Macau, Đài Loan phải gọi 010-6278 3779). Bắc Đại mở suất trước 7 ngày lúc 8:00 sáng, không cho vào khoảng 11:00–13:00, và cũng xác thực bằng số giấy tờ. Ngoài ra Thanh Hoa nhiều thời điểm chỉ mở cửa cuối tuần - mà 26/10 là thứ hai.",
       "Registering yourself is genuinely awkward: both require an advance booking through a WeChat mini-program - <span class=\"han\">参观清华</span> and <span class=\"han\">参观北大</span> - but Tsinghua's system currently accepts only mainland ID cards, not foreign passports (visitors from Hong Kong, Macau and Taiwan must call 010-6278 3779). PKU releases slots 7 days ahead at 08:00, bars entry roughly 11:00–13:00, and also verifies by ID number. Tsinghua has often been open to visitors only at weekends, too - and 26 Oct is a Monday.",
       "自己预约确实麻烦：两校都要通过微信小程序提前预约——<span class=\"han\">参观清华</span>和<span class=\"han\">参观北大</span>——但清华的系统目前只接受大陆身份证，不接受外国护照（港澳台访客须致电010-6278 3779）。北大提前7天8:00放号，11:00–13:00左右不放行，同样按证件号实名验证。此外清华多数时期只在周末对外开放——而10月26日是周一。"]],
     fix:["<strong>Nếu xin được suất vào thì đổi lịch thế này:</strong> bỏ Viên Minh Viên, dành 14:30–15:45 cho Bắc Đại (hồ Vị Danh <span class=\"han\">未名湖</span> và tháp Bác Nhã <span class=\"han\">博雅塔</span>) và 16:00–17:15 cho Thanh Hoa (<span class=\"han\">二校门</span> Nhị Hiệu Môn và đại lễ đường mái vòm đỏ). Hai khuôn viên cách nhau 15 phút đi bộ. Nhớ mang hộ chiếu bản gốc và tên người mời.",
      "<strong>If you do get in, reshape the afternoon like this:</strong> drop the Old Summer Palace, give 14:30–15:45 to PKU (Weiming Lake <span class=\"han\">未名湖</span> and Boya Pagoda) and 16:00–17:15 to Tsinghua (<span class=\"han\">二校门</span> and the red-domed auditorium). The two campuses are a 15-minute walk apart. Bring the original passport and the name of whoever invited you.",
      "<strong>若真约到了，下午这样改：</strong>去掉圆明园，14:30–15:45给北大（<span class=\"han\">未名湖</span>与博雅塔），16:00–17:15给清华（<span class=\"han\">二校门</span>与红穹顶大礼堂）。两校步行相距15分钟。记得带护照原件和邀请人姓名。"]
   }
  ]
}
);
